import {
  createBrowserRouter,
  createMemoryRouter,
  type RouteObject,
} from 'react-router-dom';
import { RouteError } from '@pizza-avenue/ui';
import { CustomerLayout } from './layout';
import {
  AuthMagicPage,
  AuthOtpPage,
  AuthPage,
  AuthWhatsAppPage,
  CartPage,
  CheckoutPage,
  CheckoutPickupPage,
  DineInBillPage,
  DineInHomePage,
  DineInOrderPage,
  DineInServicePage,
  DineInShellPage,
  DineInStartPage,
  DineInWrongTablePage,
  HomePage,
  MenuPage,
  NotFoundPage,
  OrderDetailPage,
  OrdersPage,
  PassportPage,
  PaymentFailurePage,
  PaymentPage,
  PaymentSuccessPage,
  ProductPage,
  ProfilePage,
  RewardsPage,
} from '../routes';

export const customerRoutes: RouteObject[] = [
  {
    path: '/',
    element: <CustomerLayout />,
    errorElement: <RouteError />,
    children: [
      { index: true, element: <HomePage /> },
      { path: 'menu', element: <MenuPage /> },
      { path: 'menu/:productId', element: <ProductPage /> },
      { path: 'cart', element: <CartPage /> },
      { path: 'checkout', element: <CheckoutPage /> },
      { path: 'checkout/pickup', element: <CheckoutPickupPage /> },
      { path: 'dine-in/start', element: <DineInStartPage /> },
      { path: 'dine-in/table', element: <DineInShellPage title="Confirm your table" guidance="Confirm the server-resolved table context before ordering." /> },
      { path: 'dine-in', element: <DineInHomePage /> },
      { path: 'dine-in/menu', element: <DineInShellPage title="Dine-in menu" guidance="One shared catalog, filtered by Dine-in availability." /> },
      { path: 'dine-in/menu/:productId', element: <DineInShellPage title="Dine-in product" guidance="Customize against the shared product and modifier contracts." /> },
      { path: 'dine-in/cart', element: <DineInShellPage title="Dine-in cart" guidance="This cart is separate from a saved Pickup cart." /> },
      { path: 'dine-in/review', element: <DineInShellPage title="Review your order" guidance="Send Order to Waiter. This does not confirm kitchen entry." /> },
      { path: 'dine-in/orders/:orderId', element: <DineInOrderPage /> },
      { path: 'dine-in/orders/:orderId/clarification', element: <DineInShellPage title="Your order needs attention" guidance="Your waiter needs to confirm one detail. Your selections are preserved." /> },
      { path: 'dine-in/orders/:orderId/rejected', element: <DineInShellPage title="Order not accepted" guidance="Review the reason, edit the order, or call your waiter." /> },
      { path: 'dine-in/orders/:orderId/accepted', element: <DineInShellPage title="Order accepted" guidance="Your waiter confirmed this order and sent it to the kitchen." /> },
      { path: 'dine-in/orders/:orderId/preparing', element: <DineInShellPage title="Preparing" guidance="The kitchen is preparing this round." /> },
      { path: 'dine-in/orders/:orderId/ready-to-serve', element: <DineInShellPage title="Ready to be served" guidance="A waiter or runner will bring this round to the table." /> },
      { path: 'dine-in/orders/:orderId/served', element: <DineInShellPage title="Served" guidance="Order more or review the current table bill." /> },
      { path: 'dine-in/order-more', element: <DineInShellPage title="Order more" guidance="A new round uses the same submit-to-waiter confirmation flow." /> },
      { path: 'dine-in/bill', element: <DineInBillPage /> },
      { path: 'dine-in/bill/request', element: <DineInShellPage title="Request bill" guidance="Staff will finalize and collect payment. New rounds stop after the request unless staff reopens the session." /> },
      { path: 'dine-in/service', element: <DineInServicePage /> },
      { path: 'dine-in/session-complete', element: <DineInShellPage title="Table session complete" guidance="Payment was handled by staff and the table session is closed." /> },
      { path: 'dine-in/expired', element: <DineInShellPage title="Your previous table session has ended" guidance="Scan the current table QR or choose Pickup." /> },
      { path: 'dine-in/wrong-table', element: <DineInWrongTablePage /> },
      { path: 'auth', element: <AuthPage /> },
      { path: 'auth/otp', element: <AuthOtpPage /> },
      { path: 'auth/whatsapp', element: <AuthWhatsAppPage /> },
      { path: 'auth/magic', element: <AuthMagicPage /> },
      { path: 'payment', element: <PaymentPage /> },
      { path: 'payment/success', element: <PaymentSuccessPage /> },
      { path: 'payment/failure', element: <PaymentFailurePage /> },
      { path: 'orders', element: <OrdersPage /> },
      { path: 'orders/:orderId', element: <OrderDetailPage /> },
      { path: 'rewards', element: <RewardsPage /> },
      { path: 'passport', element: <PassportPage /> },
      { path: 'profile', element: <ProfilePage /> },
      { path: '*', element: <NotFoundPage /> },
    ],
  },
];

export const customerRouter = createBrowserRouter(customerRoutes);

export function createCustomerMemoryRouter(initialEntries: string[] = ['/']) {
  return createMemoryRouter(customerRoutes, { initialEntries });
}
